### ISSUE TITLE
Investigate how to do nested menus

### ISSUE THREAD

**Issue by daliborduric** [coremind-oss/ttasm-desktop-app#2]
I'll take a look at my own code, but you should all try to do the research on your own.

**Comment by Racapa** [comment]
I did some research and I came up with: 

`QAction QMenu.addMenu (self, QMenu menu)`
Desc: This convenience function adds menu as a submenu to this menu. It returns menu's menuAction(). This menu does not take ownership of menu.

`QAction QMenu.menuAction (self)`
Decs: Returns the action associated with this menu.

I'm not really sure what 'QAction' represents in those methods since they are from QMenu class. I was doing the research of QAction class and it seems that there aren't methods called addMenu() and menuAction().

In my opinion, submenu is added as 'action' of main menu. This way the new menu (which is actualy a submenu of main menu) doesn't take the ownership over the main menu, so it doesn't replace it as a "new" main menu. I hope I got it right way.

**Comment by daliborduric** [comment]
you can use **<>** button in this message form for inserting code
then it will look like this:
`QAction QMenu.addMenu (self, QMenu menu)`

**Comment by LukaDjordjevic** [comment]
Here is a working submenus example. The code below replaces entire tray.py. Tried to push it to github but i guess i don't have the privileges.

`import sys
from time import sleep

from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMenu
from PyQt5.QtWidgets import QSystemTrayIcon


class SystemTrayIcon(QSystemTrayIcon):

    def __init__(self):
        QSystemTrayIcon.__init__(self, QIcon('icons/icon-placeholder_128x128.png'))
        
        # Initialize menu
        mainMenu = QMenu()
        mainMenu.setTitle("Main Menu")
        
        # Create submenus and populate them with items
        subMenu1 = QMenu(mainMenu)
        subMenu1.setTitle('Submenu1') # Not sure what this does
        subMenu1ButtonA=subMenu1.addAction("Action A")
        subMenu1ButtonA.triggered.connect(self.subMenu1ButtonAAction)
        subMenu1.addAction("Action B")
        subMenu1.addAction("Action B")

        subMenu2 = QMenu(mainMenu)
        subMenu2.setTitle('Submenu2')
        subMenu2.addAction("Action D")
        subMenu2.addAction("Action E")
        subMenu2.addAction("Action F")      
          
        # Populate Main Menu
        mainMenu.addMenu(subMenu1)
        menu1Button = mainMenu.addAction("Menu1")
        menu1Button.triggered.connect(self.menu1Action)
       
        mainMenu.addMenu(subMenu2)
        
        exitButton = mainMenu.addAction("Exit")
        exitButton.triggered.connect(self.quit)
 
 
                 
        # Set the menu as context menu
        self.setContextMenu(mainMenu)
   
    def menu1Action(self):
        print ("MainMenu button2 stuff")
        
    def subMenu1ButtonAAction(self):
        print ("Submenu1 First button stuff")
        
    def quit(self):
        print ('Clean exit')
        sys.exit(0)`

**Comment by daliborduric** [comment]
You need to create a branch and then a pull request into development

**Comment by LukaDjordjevic** [comment]
I'm having trouble pushing, it says:

(development-01)luka@djordjevic:~/workspace/ttasm-desktop-app$ git push origin development
Username for 'https://github.com': lukadjordjevic
Password for 'https://lukadjordjevic@github.com': 
remote: Permission to coremind-oss/ttasm-desktop-app.git denied to LukaDjordjevic.

**Comment by LukaDjordjevic** [comment]
Trying to find you guys. Don't have slack on my phone. Can you give me a call 064 353 2680
